### ISSUE TITLE
Predator mutations do nothing to prevent skill rust of combat skills

### ISSUE THREAD

**Issue by Pie-Pinkerton** [Coolthulhu/Cataclysm-DDA#7559]
### Describe the bug

The description of the latter three predator mutations (Apex Predator, Predator, and Hunter) imply that combat skills are "more easily learned and **maintained**." I interpret "maintained" as meaning, they rust slower, assuming the player has skill rust enabled. However, no such relative increase in skill retention is observed.

### Steps To Reproduce

0. enable skill rust
1. mutate apex predator
2. set all skills to a big number
3. wait a few hours
4. observe that the combat skills have rusted at the same rate as all the other skills

### Versions and configuration

- OS: Linux
    - OS Version: Distributor ID: Debian; Description: Debian GNU/Linux 13 (trixie); Release: 13; Codename: trixie; 
- Game Version: f4661e4 [64-bit]
- Graphics Version: Curses
- LAPI Version: 2
- Save File Version: V2 (compressed with sqlite 3)
- Game Language: English [en_US]
- Mods loaded: [
    Bright Nights [bn],
    No Rail Stations [No_Rail_Stations],
    Weather Variants [weather_variants],
    Tablet e-book [tablet_ebook],
    Bionic Slots [cbm_slots],
    No Monsters [Only_Wildlife]
]

### Additional context

I tested this with vanilla and INT based skill rust.

**Comment by mythosmod** [comment]
Hi @Pie-Pinkerton — this should already be working in current `main`. I traced through the skill rust code and found that predator-trait combat-skill rust prevention was added by #8411 (merged 2026-03-31), which post-dates your tested version `f4661e4` (2025-11-26) by about 4 months.

In current main, [`Character::do_skill_rust` at character.cpp:4340-4368](https://github.com/cataclysmbn/Cataclysm-BN/blob/main/src/character.cpp#L4340-L4368) reads:

```cpp
const int pred_tick = has_trait_flag( trait_flag_PRED2 ) ? calendar::ticks_between( duration, 8_hours ) :
                      has_trait_flag( trait_flag_PRED3 ) ? calendar::ticks_between( duration, 4_hours ) :
                      has_trait_flag( trait_flag_PRED4 ) ? calendar::ticks_between( duration, 3_hours ) : 0;

if( aSkill.is_combat_skill() && pred_tick > 0 ) {
    // Their brain is optimized to remember this
    ...
    continue;  // skips the rust path entirely
}
```

So for any character with PRED2 / PRED3 / PRED4, combat skills (anything tagged `combat_skill` in `data/json/skills.json` — archery, pistol, rifle, melee, dodge, etc.) skip rust entirely via the unconditional `continue`.

Could you retest with a current experimental build and confirm the behavior is now what the description promises? If it is, the issue can be closed.

**Comment by nfvelten** [comment]
Tested this on current main and the bug is still there, the fix in #8411 doesn't actually work in practice.

The `continue` that skips rust for combat skills only fires when `pred_tick > 0`, which only happens when a single `do_skill_rust` call's `duration` spans a whole 3/4/8 hour block. That's true for NPC catch-up (loading, off-screen simulation), but during normal active play `update_body()` gets called every turn with `duration == 1_turns`, so `pred_tick` is basically always 0 and the protection never engages. Meanwhile the actual rust check fires on its own much shorter interval based on skill level, so combat skills keep rusting normally the vast majority of the time.

Confirmed with a Catch2 test that simulates real turn-by-turn play, and also manually in a compiled build (PRED4, melee and fabrication both at level 8, SKILL_RUST=vanilla, walked ~2400 real turns): melee rusted 8→7 exactly like fabrication.

PR with the fix: https://github.com/cataclysmbn/Cataclysm-BN/pull/10179
